name: Supabase Keep Alive

on:
  schedule:
    # Esegue il job ogni giorno alle 12:00 UTC
    - cron: "0 12 * * *"
  workflow_dispatch: # Ti permette di avviarlo a mano per testare se funziona

jobs:
  ping_supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Database via REST API
        run: |
          curl -X GET "https://evbgthhyaayjjhhihnyv.supabase.co/rest/v1/configurations?select=*" \
          -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" \
          -I
